MUD_HOST = "prometheus-enterprises.com"
MUD_PORT = 2223

# Sessões
SESSION_TIMEOUT_MINUTES = 10
SESSION_REMOVAL_DELAY_SECONDS = 30
SESSION_CLEANUP_INTERVAL_SECONDS = 60

# MUD IO
MUD_READ_BUFFER_SIZE = 4096
MUD_IDLE_SLEEP_SECONDS = 0.05
MUD_QUIT_GRACE_SECONDS = 0.5

# Histórico (limites)
HISTORY_MAX_BYTES = 2 * 1024 * 1024
HISTORY_MAX_LINES = 4000
